version: '3.8'

services:

  rust-app:
    build:
      context: ./RustRocket
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=mysql://root:bobo2004@mysql:3306/userdata
      - ROCKET_SECRET_KEY=8Zui5ChEXtRwR+akH9PRr9oh9b1w/VGVOYDwbp3sEYM=
    depends_on:
      - mysql
    command: ["./target/release/rockettest"]

  react-app:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/node_modules
      - /react-frontend/node_modules

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bobo2004
      MYSQL_DATABASE: userdata
      MYSQL_USER: bobo
      MYSQL_PASSWORD: bobo2004
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
